export type FeedFormat = "short" | "article";
export type FeedRiskLevel = "low" | "medium" | "high";

export type FeedItem = {
  id: string;
  title: string;
  summary: string;
  bodyMarkdown?: string;
  category: string;
  sport: string;
  sourceName: string;
  sourceUrl?: string;
  imageUrl?: string;
  imageAlt?: string;
  imagePageUrl?: string;
  imageAuthor?: string;
  imageLicense?: string;
  imageLicenseUrl?: string;
  imageFocusX?: number;
  imageFocusY?: number;
  slug: string;
  format: FeedFormat;
  publishedAt: string;
  readTimeMinutes?: number;
  status?: "published" | "queued" | "draft" | "review";
  label?: string;
  lead?: string;
  whyItMatters?: string;
  practicalAction?: string;
  priorityScore?: number;
  isFeatured?: boolean;
  shortNewsPossible?: boolean;
  draftRecommended?: boolean;
  riskLevel?: FeedRiskLevel;
  possibleDuplicate?: boolean;
  topicKey?: string;
  featured?: boolean;
};
