export type FeedFormat = "short" | "article";
export type FeedRiskLevel = "low" | "medium" | "high";

export type FeedItem = {
  id: string;
  title: string;
  summary: string;
  bodyMarkdown?: string;
  matchStats?: MatchStats;
  category: string;
  sport: string;
  sourceName: string;
  sourceUrl?: string;
  imageUrl?: string;
  imageAlt?: string;
  imagePageUrl?: string;
  imageAuthor?: string;
  imageLicense?: string;
  imageLicenseUrl?: string;
  imageFocusX?: number;
  imageFocusY?: number;
  slug: string;
  format: FeedFormat;
  publishedAt: string;
  readTimeMinutes?: number;
  status?: "published" | "queued" | "draft" | "review";
  label?: string;
  lead?: string;
  whyItMatters?: string;
  practicalAction?: string;
  priorityScore?: number;
  isFeatured?: boolean;
  shortNewsPossible?: boolean;
  draftRecommended?: boolean;
  riskLevel?: FeedRiskLevel;
  possibleDuplicate?: boolean;
  topicKey?: string;
  featured?: boolean;
};

export type MatchStats = {
  competition?: string;
  event?: string;
  status?: string;
  home_team?: string;
  away_team?: string;
  final_score?: string;
  periods?: Array<{ label?: string; home?: string | number; away?: string | number }>;
  leaders?: Array<{ label?: string; player?: string; value?: string | number }>;
  team_stats?: Array<{ label?: string; home?: string | number; away?: string | number }>;
  note?: string;
};
